# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/ninelore/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Path to your oh-my-zsh installation.
export ZSH="/home/ninelore/.oh-my-zsh"

# Set name of the theme to load --- "themename" or "random"
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="nicoulaj"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Timestamp format
HIST_STAMPS="yyyy-mm-dd"

# ZSH Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Custom Enviromental Vars
export WINUSER="/mnt/c/Users/ingor"
export GCM_CREDENTIAL_STORE="gpg"
export GPG_TTY=$(tty)

# Custon Aliases
bindkey -v

alias v='nvim'
alias untar='tar -zxvf'
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias sv='sudo nvim'
alias root='sudo -i'
alias su='sudo -i'
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
alias upall="sudo apt update && sudo apt upgrade"
alias r='ranger'
alias sr='sudo ranger'
alias c='clear'
alias cryptopen='sudo cryptsetup open'
alias cryptclose='sudo cryptsetup close'
alias py='python3'
alias py2='python2'
alias cdw='cd $WINUSER'
